### Step 1: Install required libraries

In [1]:
!pip install datasets pandas pymupdf pageindex groq python-dotenv ipykernel openai

Collecting datasets
  Using cached datasets-4.8.4-py3-none-any.whl.metadata (19 kB)
Collecting pandas
  Using cached pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting pymupdf
  Using cached pymupdf-1.27.2.2-cp310-abi3-win_amd64.whl.metadata (3.4 kB)
Collecting pageindex
  Using cached pageindex-0.2.8-py3-none-any.whl.metadata (628 bytes)
Collecting groq
  Using cached groq-1.2.0-py3-none-any.whl.metadata (16 kB)
Collecting python-dotenv
  Using cached python_dotenv-1.2.2-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: ipykernel in .\.venv\Lib\site-packages (7.2.0)
Collecting openai
  Using cached openai-2.32.0-py3-none-any.whl.metadata (31 kB)
Collecting filelock (from datasets)
  Using cached filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
Collecting numpy>=1.17 (from datasets)
  Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Collecting pyarrow>=21.0.0 (from datasets)
  Using cached pyarrow-23.0.1-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting requests>=2.32.2 (from datasets)
  Using cached requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting httpx<1.0.0 (from datasets)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting tqdm>=4.66.3 (from datasets)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting xxhash (from datasets)
  Using cached xxhash-3.6.0-cp312-cp312-win_amd64.whl.metadata (13 kB)
Collecting multiprocess<0.70.20 (from datasets)
  Using cached multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting fsspec<=2026.2.0,>=2023.1.0 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached fsspec-2026.2.0-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<2.0,>=0.25.0 (from datasets)
  Using cached huggingface_hub-1.11.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: packaging in .\.venv\Lib\site-packages (from datasets) (26.1)
Collecting pyyaml>=5.1 (from datasets)
  Using cached pyyaml-6.0.3-cp312-cp312-win_amd64.whl.metadata (2.4 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohttp-3.13.5-cp312-cp312-win_amd64.whl.metadata (8.4 kB)
Collecting anyio (from httpx<1.0.0->datasets)
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting certifi (from httpx<1.0.0->datasets)
  Using cached certifi-2026.2.25-py3-none-any.whl.metadata (2.5 kB)
Collecting httpcore==1.* (from httpx<1.0.0->datasets)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx<1.0.0->datasets)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1.0.0->datasets)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached hf_xet-1.4.3-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting typer (from huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached typer-0.24.1-py3-none-any.whl.metadata (16 kB)
Collecting typing-extensions>=4.1.0 (from huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.32.2->datasets)
  Using cached charset_normalizer-3.4.7-cp312-cp312-win_amd64.whl.metadata (41 kB)
Collecting urllib3<3,>=1.26 (from requests>=2.32.2->datasets)
  Using cached urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting distro<2,>=1.7.0 (from groq)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting pydantic<3,>=1.9.0 (from groq)
  Downloading pydantic-2.13.3-py3-none-any.whl.metadata (108 kB)
Collecting sniffio (from groq)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3,>=1.9.0->groq)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.3 (from pydantic<3,>=1.9.0->groq)
  Downloading pydantic_core-2.46.3-cp312-cp312-win_amd64.whl.metadata (6.7 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3,>=1.9.0->groq)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: comm>=0.1.1 in .\.venv\Lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in .\.venv\Lib\site-packages (from ipykernel) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in .\.venv\Lib\site-packages (from ipykernel) (9.12.0)
Requirement already satisfied: jupyter-client>=8.8.0 in .\.venv\Lib\site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in .\.venv\Lib\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in .\.venv\Lib\site-packages (from ipykernel) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in .\.venv\Lib\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: psutil>=5.7 in .\.venv\Lib\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in .\.venv\Lib\site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in .\.venv\Lib\site-packages (from ipykernel) (6.5.5)
Requirement already satisfied: traitlets>=5.4.0 in .\.venv\Lib\site-packages (from ipykernel) (5.14.3)
Collecting jiter<1,>=0.10.0 (from openai)
  Using cached jiter-0.14.0-cp312-cp312-win_amd64.whl.metadata (5.3 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached frozenlist-1.8.0-cp312-cp312-win_amd64.whl.metadata (21 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached multidict-6.7.1-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached propcache-0.4.1-cp312-cp312-win_amd64.whl.metadata (14 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets)
  Using cached yarl-1.23.0-cp312-cp312-win_amd64.whl.metadata (82 kB)
Requirement already satisfied: colorama>=0.4.4 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in .\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth in .\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in .\.venv\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.6)
Requirement already satisfied: platformdirs>=2.5 in .\.venv\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.9.6)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: pure-eval in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)
Collecting click>=8.2.1 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached click-8.3.2-py3-none-any.whl.metadata (2.6 kB)
Collecting shellingham>=1.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=12.3.0 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached datasets-4.8.4-py3-none-any.whl (526 kB)
Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Using cached fsspec-2026.2.0-py3-none-any.whl (202 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached huggingface_hub-1.11.0-py3-none-any.whl (645 kB)
Using cached hf_xet-1.4.3-cp37-abi3-win_amd64.whl (3.7 MB)
Using cached multiprocess-0.70.19-py312-none-any.whl (150 kB)
Using cached pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
Using cached pymupdf-1.27.2.2-cp310-abi3-win_amd64.whl (19.2 MB)
Using cached pageindex-0.2.8-py3-none-any.whl (6.0 kB)
Using cached requests-2.33.1-py3-none-any.whl (64 kB)
Using cached charset_normalizer-3.4.7-cp312-cp312-win_amd64.whl (159 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Using cached urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached groq-1.2.0-py3-none-any.whl (142 kB)
Using cached anyio-4.13.0-py3-none-any.whl (114 kB)
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Downloading pydantic-2.13.3-py3-none-any.whl (471 kB)
Downloading pydantic_core-2.46.3-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   --------------- ------------------------ 0.8/2.1 MB 4.2 MB/s eta 0:00:01
   ----------------------------------- ---- 1.8/2.1 MB 4.4 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.3 MB/s  0:00:00
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Using cached python_dotenv-1.2.2-py3-none-any.whl (22 kB)
Using cached openai-2.32.0-py3-none-any.whl (1.2 MB)
Using cached jiter-0.14.0-cp312-cp312-win_amd64.whl (201 kB)
Using cached aiohttp-3.13.5-cp312-cp312-win_amd64.whl (460 kB)
Using cached multidict-6.7.1-cp312-cp312-win_amd64.whl (46 kB)
Using cached yarl-1.23.0-cp312-cp312-win_amd64.whl (87 kB)
Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached certifi-2026.2.25-py3-none-any.whl (153 kB)
Using cached filelock-3.29.0-py3-none-any.whl (39 kB)
Using cached frozenlist-1.8.0-cp312-cp312-win_amd64.whl (44 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
Using cached propcache-0.4.1-cp312-cp312-win_amd64.whl (41 kB)
Using cached pyarrow-23.0.1-cp312-cp312-win_amd64.whl (27.6 MB)
Using cached pyyaml-6.0.3-cp312-cp312-win_amd64.whl (154 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached typer-0.24.1-py3-none-any.whl (56 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached click-8.3.2-py3-none-any.whl (108 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Using cached tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Using cached xxhash-3.6.0-cp312-cp312-win_amd64.whl (31 kB)
Installing collected packages: xxhash, urllib3, tzdata, typing-extensions, tqdm, sniffio, shellingham, pyyaml, python-dotenv, pymupdf, pyarrow, propcache, numpy, multidict, mdurl, jiter, idna, hf-xet, h11, fsspec, frozenlist, filelock, distro, dill, click, charset_normalizer, certifi, attrs, annotated-types, annotated-doc, aiohappyeyeballs, yarl, typing-inspection, requests, pydantic-core, pandas, multiprocess, markdown-it-py, httpcore, anyio, aiosignal, rich, pydantic, httpx, aiohttp, typer, openai, groq, pageindex, huggingface-hub, datasets

    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
    ---------------------------------------  1/51 [urllib3]
   - --------------------------------------  2/51 [tzdata]
   - --------------------------------------  2/51 [tzdata]
   - --------------------------------------  2/51 [tzdata]
   - --------------------------------------  2/51 [tzdata]
   - --------------------------------------  2/51 [tzdata]
   -- -------------------------------------  3/51 [typing-extensions]
   --- ------------------------------------  4/51 [tqdm]
   --- ------------------------------------  4/51 [tqdm]
   --- ------------------------------------  4/51 [tqdm]
   --- ------------------------------------  4/51 [tqdm]
   --- ------------------------------------  4/51 [tqdm]
   --- ------------------------------------  5/51 [sniffio]
   ---- -----------------------------------  6/51 [shellingham]
   ----- ----------------------------------  7/51 [pyyaml]
   ----- ----------------------------------  7/51 [pyyaml]
   ----- ----------------------------------  7/51 [pyyaml]
   ------ ---------------------------------  8/51 [python-dotenv]
   ------ ---------------------------------  8/51 [python-dotenv]
   ------ ---------------------------------  8/51 [python-dotenv]
   ------- --------------------------------  9/51 [pymupdf]
   ------- --------------------------------  9/51 [pymupdf]
   ------- --------------------------------  9/51 [pymupdf]
   ------- --------------------------------  9/51 [pymupdf]
   ------- --------------------------------  9/51 [pymupdf]
   ------- --------------------------------  9/51 [pymupdf]
   ------- --------------------------------  9/51 [pymupdf]
   ------- --------------------------------  9/51 [pymupdf]
   ------- --------------------------------  9/51 [pymupdf]
   ------- --------------------------------  9/51 [pymupdf]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   ------- -------------------------------- 10/51 [pyarrow]
   -------- ------------------------------- 11/51 [propcache]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]
   --------- ------------------------------ 12/51 [numpy]

In [4]:
!pip install -U ipywidgets jupyter

Collecting ipywidgets
  Using cached ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyter
  Using cached jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: comm>=0.1.3 in .\.venv\Lib\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in .\.venv\Lib\site-packages (from ipywidgets) (9.12.0)
Requirement already satisfied: traitlets>=4.3.1 in .\.venv\Lib\site-packages (from ipywidgets) (5.14.3)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets)
  Using cached widgetsnbextension-4.0.15-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets)
  Using cached jupyterlab_widgets-3.0.16-py3-none-any.whl.metadata (20 kB)
Collecting notebook (from jupyter)
  Downloading notebook-7.5.5-py3-none-any.whl.metadata (10 kB)
Collecting jupyter-console (from jupyter)
  Using cached jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Collecting nbconvert (from jupyter)
  Downloading nbconvert-7.17.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: ipykernel in .\.venv\Lib\site-packages (from jupyter) (7.2.0)
Collecting jupyterlab (from jupyter)
  Downloading jupyterlab-4.5.6-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: colorama>=0.4.4 in .\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in .\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in .\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in .\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline>=0.1.6 in .\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.2.1)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in .\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in .\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in .\.venv\Lib\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in .\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in .\.venv\Lib\site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.6)
Requirement already satisfied: executing>=1.2.0 in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in .\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in .\.venv\Lib\site-packages (from ipykernel->jupyter) (1.8.20)
Requirement already satisfied: jupyter-client>=8.8.0 in .\.venv\Lib\site-packages (from ipykernel->jupyter) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in .\.venv\Lib\site-packages (from ipykernel->jupyter) (5.9.1)
Requirement already satisfied: nest-asyncio>=1.4 in .\.venv\Lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: packaging>=22 in .\.venv\Lib\site-packages (from ipykernel->jupyter) (26.1)
Requirement already satisfied: psutil>=5.7 in .\.venv\Lib\site-packages (from ipykernel->jupyter) (7.2.2)
Requirement already satisfied: pyzmq>=25 in .\.venv\Lib\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in .\.venv\Lib\site-packages (from ipykernel->jupyter) (6.5.5)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from jupyter-client>=8.8.0->ipykernel->jupyter) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in .\.venv\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->jupyter) (4.9.6)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.8.0->ipykernel->jupyter) (1.17.0)
Collecting async-lru>=1.0.0 (from jupyterlab->jupyter)
  Downloading async_lru-2.3.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: httpx<1,>=0.25.0 in .\.venv\Lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Collecting jinja2>=3.0.3 (from jupyterlab->jupyter)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jupyter-lsp>=2.0.0 (from jupyterlab->jupyter)
  Downloading jupyter_lsp-2.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting jupyter-server<3,>=2.4.0 (from jupyterlab->jupyter)
  Using cached jupyter_server-2.17.0-py3-none-any.whl.metadata (8.5 kB)
Collecting jupyterlab-server<3,>=2.28.0 (from jupyterlab->jupyter)
  Using cached jupyterlab_server-2.28.0-py3-none-any.whl.metadata (5.9 kB)
Collecting notebook-shim>=0.2 (from jupyterlab->jupyter)
  Using cached notebook_shim-0.2.4-py3-none-any.whl.metadata (4.0 kB)
Collecting setuptools>=41.1.0 (from jupyterlab->jupyter)
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: anyio in .\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.13.0)
Requirement already satisfied: certifi in .\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2026.2.25)
Requirement already satisfied: httpcore==1.* in .\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: idna in .\.venv\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.11)
Requirement already satisfied: h11>=0.16 in .\.venv\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Collecting argon2-cffi>=21.1 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached argon2_cffi-25.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting jupyter-events>=0.11.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached jupyter_events-0.12.0-py3-none-any.whl.metadata (5.8 kB)
Collecting jupyter-server-terminals>=0.4.4 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl.metadata (5.9 kB)
Collecting nbformat>=5.3.0 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Collecting prometheus-client>=0.9 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading prometheus_client-0.25.0-py3-none-any.whl.metadata (2.1 kB)
Collecting pywinpty>=2.0.1 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading pywinpty-3.0.3-cp312-cp312-win_amd64.whl.metadata (5.9 kB)
Collecting send2trash>=1.8.2 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading send2trash-2.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting terminado>=0.8.3 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached terminado-0.18.1-py3-none-any.whl.metadata (5.8 kB)
Collecting websocket-client>=1.7 (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached websocket_client-1.9.0-py3-none-any.whl.metadata (8.3 kB)
Collecting babel>=2.10 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached babel-2.18.0-py3-none-any.whl.metadata (2.2 kB)
Collecting json5>=0.9.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Downloading json5-0.14.0-py3-none-any.whl.metadata (36 kB)
Collecting jsonschema>=4.18.0 (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: requests>=2.31 in .\.venv\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.33.1)
Requirement already satisfied: typing_extensions>=4.5 in .\.venv\Lib\site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab->jupyter) (4.15.0)
Collecting argon2-cffi-bindings (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached argon2_cffi_bindings-25.1.0-cp39-abi3-win_amd64.whl.metadata (7.5 kB)
Collecting MarkupSafe>=2.0 (from jinja2>=3.0.3->jupyterlab->jupyter)
  Using cached markupsafe-3.0.3-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: attrs>=22.2.0 in .\.venv\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter)
  Using cached rpds_py-0.30.0-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Collecting python-json-logger>=2.0.4 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Downloading python_json_logger-4.1.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: pyyaml>=5.3 in .\.venv\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.3)
Collecting rfc3339-validator (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached rfc3339_validator-0.1.4-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting rfc3986-validator>=0.1.1 (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Collecting jsonpointer>1.13 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached jsonpointer-3.1.1-py3-none-any.whl.metadata (2.4 kB)
Collecting rfc3987-syntax>=1.1.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached rfc3987_syntax-1.1.0-py3-none-any.whl.metadata (7.7 kB)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Collecting beautifulsoup4 (from nbconvert->jupyter)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting bleach!=5.0.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached bleach-6.3.0-py3-none-any.whl.metadata (31 kB)
Collecting defusedxml (from nbconvert->jupyter)
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
Collecting jupyterlab-pygments (from nbconvert->jupyter)
  Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl.metadata (4.4 kB)
Collecting mistune<4,>=2.0.3 (from nbconvert->jupyter)
  Downloading mistune-3.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting nbclient>=0.5.0 (from nbconvert->jupyter)
  Downloading nbclient-0.10.4-py3-none-any.whl.metadata (8.3 kB)
Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter)
  Using cached pandocfilters-1.5.1-py2.py3-none-any.whl.metadata (9.0 kB)
Collecting webencodings (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting tinycss2<1.5,>=1.1.0 (from bleach[css]!=5.0.0->nbconvert->jupyter)
  Using cached tinycss2-1.4.0-py3-none-any.whl.metadata (3.0 kB)
Collecting fastjsonschema>=2.15 (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in .\.venv\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in .\.venv\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.6.3)
Collecting lark>=1.2.2 (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached lark-1.3.1-py3-none-any.whl.metadata (1.8 kB)
Collecting cffi>=1.0.1 (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached cffi-2.0.0-cp312-cp312-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->nbconvert->jupyter)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting arrow>=0.15.0 (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter)
  Using cached arrow-1.4.0-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2026.1)
Using cached ipywidgets-8.1.8-py3-none-any.whl (139 kB)
Using cached jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
Using cached widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
Using cached jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Using cached jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Downloading jupyterlab-4.5.6-py3-none-any.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.4 MB 3.1 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/12.4 MB 3.0 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.4 MB 2.7 MB/s eta 0:00:04
   --------- ------------------------------ 2.9/12.4 MB 2.8 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.4 MB 2.9 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.4 MB 2.8 MB/s eta 0:00:04
   -------------- ------------------------- 4.5/12.4 MB 2.7 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.4 MB 2.7 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.4 MB 2.8 MB/s eta 0:00:03
   -------------------- ------------------- 6.3/12.4 MB 2.7 MB/s eta 0:00:03
   ---------------------- ----------------- 7.1/12.4 MB 2.8 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.4 MB 2.9 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.4 MB 2.9 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.4 MB 2.9 MB/s eta 0:00:02
   ------------------------------- -------- 9.7/12.4 MB 2.9 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.4 MB 2.9 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.4 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.4 MB 2.7 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.4 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 2.8 MB/s  0:00:04
Using cached jupyter_server-2.17.0-py3-none-any.whl (388 kB)
Using cached jupyterlab_server-2.28.0-py3-none-any.whl (59 kB)
Using cached argon2_cffi-25.1.0-py3-none-any.whl (14 kB)
Downloading async_lru-2.3.0-py3-none-any.whl (8.4 kB)
Using cached babel-2.18.0-py3-none-any.whl (10.2 MB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading json5-0.14.0-py3-none-any.whl (36 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Using cached jupyter_events-0.12.0-py3-none-any.whl (19 kB)
Using cached jsonpointer-3.1.1-py3-none-any.whl (7.7 kB)
Downloading jupyter_lsp-2.3.1-py3-none-any.whl (77 kB)
Downloading jupyter_server_terminals-0.5.4-py3-none-any.whl (13 kB)
Using cached markupsafe-3.0.3-cp312-cp312-win_amd64.whl (15 kB)
Downloading nbconvert-7.17.1-py3-none-any.whl (261 kB)
Downloading mistune-3.2.0-py3-none-any.whl (53 kB)
Using cached bleach-6.3.0-py3-none-any.whl (164 kB)
Using cached tinycss2-1.4.0-py3-none-any.whl (26 kB)
Downloading nbclient-0.10.4-py3-none-any.whl (25 kB)
Using cached nbformat-5.10.4-py3-none-any.whl (78 kB)
Using cached fastjsonschema-2.21.2-py3-none-any.whl (24 kB)
Using cached notebook_shim-0.2.4-py3-none-any.whl (13 kB)
Using cached pandocfilters-1.5.1-py2.py3-none-any.whl (8.7 kB)
Downloading prometheus_client-0.25.0-py3-none-any.whl (64 kB)
Downloading python_json_logger-4.1.0-py3-none-any.whl (15 kB)
Downloading pywinpty-3.0.3-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   -------------- ------------------------- 0.8/2.1 MB 3.0 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 4.2 MB/s  0:00:00
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Using cached rfc3986_validator-0.1.1-py2.py3-none-any.whl (4.2 kB)
Using cached rfc3987_syntax-1.1.0-py3-none-any.whl (8.0 kB)
Using cached lark-1.3.1-py3-none-any.whl (113 kB)
Using cached rpds_py-0.30.0-cp312-cp312-win_amd64.whl (240 kB)
Downloading send2trash-2.1.0-py3-none-any.whl (17 kB)
Downloading setuptools-82.0.1-py3-none-any.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ------------------------------- -------- 0.8/1.0 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 1.0/1.0 MB 2.6 MB/s  0:00:00
Using cached terminado-0.18.1-py3-none-any.whl (14 kB)
Using cached webcolors-25.10.0-py3-none-any.whl (14 kB)
Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Using cached websocket_client-1.9.0-py3-none-any.whl (82 kB)
Using cached argon2_cffi_bindings-25.1.0-cp39-abi3-win_amd64.whl (31 kB)
Using cached cffi-2.0.0-cp312-cp312-win_amd64.whl (183 kB)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.3-py3-none-any.whl (37 kB)
Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Using cached fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Using cached isoduration-20.11.0-py3-none-any.whl (11 kB)
Using cached arrow-1.4.0-py3-none-any.whl (68 kB)
Using cached jupyterlab_pygments-0.3.0-py3-none-any.whl (15 kB)
Downloading notebook-7.5.5-py3-none-any.whl (14.6 MB)
   ---------------------------------------- 0.0/14.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/14.6 MB 3.3 MB/s eta 0:00:05
   ---- ----------------------------------- 1.6/14.6 MB 3.4 MB/s eta 0:00:04
   ----- ---------------------------------- 2.1/14.6 MB 3.1 MB/s eta 0:00:05
   ------- -------------------------------- 2.6/14.6 MB 3.1 MB/s eta 0:00:04
   --------- ------------------------------ 3.4/14.6 MB 3.1 MB/s eta 0:00:04
   ----------- ---------------------------- 4.2/14.6 MB 3.3 MB/s eta 0:00:04
   ------------- -------------------------- 5.0/14.6 MB 3.3 MB/s eta 0:00:03
   --------------- ------------------------ 5.5/14.6 MB 3.2 MB/s eta 0:00:03
   ----------------- ---------------------- 6.3/14.6 MB 3.3 MB/s eta 0:00:03
   -------------------- ------------------- 7.3/14.6 MB 3.4 MB/s eta 0:00:03

In [5]:
import datasets
import pandas as pd
import fitz          # PyMuPDF
import pageindex
import groq
import dotenv
import openai

print("All imports successful")

import ipywidgets
print("ipywidgets installed")

All imports successful
ipywidgets installed

### Step 2: Downloand dataset

In [6]:
from datasets import load_dataset
import pandas as pd

# Download dataset
dataset = load_dataset("RahulS3/siddha_vaithiyam_question_answering_chatbot")

print(dataset)

# Convert train split to DataFrame
df = pd.DataFrame(dataset["train"])

# Save locally
df.to_csv("siddha_dataset.csv", index=False, encoding="utf-8")

print("Saved as siddha_dataset.csv")

# Inspect columns and first rows
print(df.columns)
print(df.head())

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

DatasetDict({
    train: Dataset({
        features: ['Questions', 'Answers'],
        num_rows: 1084
    })
})
Saved as siddha_dataset.csv
Index(['Questions', 'Answers'], dtype='str')
             Questions                                            Answers
0         குடியை மறக்க  வில்வ இலை, மிளகு, கொத்தமல்லி விதை இந்த மூன்றைய...
1             செல்போன்  செல்போன் அடிக்கடி உபயோகித்தால் மூளை மந்தம், கா...
2        முகம் பளபளக்க  நாட்டு வாழைப்பழம் நன்றாக பழுத்தது. ஆலிவ் ஆயில்...
3  முகச்சுருக்கம் மறைய             முட்டைகோஸ் சாறை முகத்தில் தடவி வரலாம்.
4   உடல் மினுமினுப்பாக  இரவில் படுக்கப் போகும் முன் தேன், குங்குமப்பூ....

### Step 3:Clean the dataset

In [7]:
# Check original columns first
print(df.columns)

# Rename columns
df = df.rename(columns={
    "Questions": "question",
    "Answers": "answer"
})

# Keep only required columns
df = df[["question", "answer"]]

# Remove nulls
df = df.dropna()

# Convert to string and strip spaces
df["question"] = df["question"].astype(str).str.strip()
df["answer"] = df["answer"].astype(str).str.strip()

# Remove empty rows
df = df[(df["question"] != "") & (df["answer"] != "")]

# Optional: remove duplicate question-answer pairs
df = df.drop_duplicates(subset=["question", "answer"]).reset_index(drop=True)

# Add serial number
df.insert(0, "s.no", range(1, len(df) + 1))

# Save clean CSV
df.to_csv("siddha_clean.csv", index=False, encoding="utf-8")

print("Clean CSV saved!")
print("Total rows:", len(df))

df.head()

Index(['Questions', 'Answers'], dtype='str')
Clean CSV saved!
Total rows: 1082

,s.no,question,answer
0,1,குடியை மறக்க,"வில்வ இலை, மிளகு, கொத்தமல்லி விதை இந்த மூன்றைய..."
1,2,செல்போன்,"செல்போன் அடிக்கடி உபயோகித்தால் மூளை மந்தம், கா..."
2,3,முகம் பளபளக்க,நாட்டு வாழைப்பழம் நன்றாக பழுத்தது. ஆலிவ் ஆயில்...
3,4,முகச்சுருக்கம் மறைய,முட்டைகோஸ் சாறை முகத்தில் தடவி வரலாம்.
4,5,உடல் மினுமினுப்பாக,"இரவில் படுக்கப் போகும் முன் தேன், குங்குமப்பூ...."

In [8]:
import pandas as pd

df = pd.read_csv("siddha_clean.csv")

print(df.head())
print("Total rows:", len(df))

clean_data = []

for _, row in df.iterrows():
    q = str(row["question"]).strip()
    a = str(row["answer"]).strip()

    q = " ".join(q.split())
    a = " ".join(a.split())

    clean_data.append({
        "id": int(row["s.no"]),
        "question": q,
        "answer": a
    })

print(clean_data[:3])

def chunk_data(data, size=50):
    for i in range(0, len(data), size):
        yield data[i:i+size]

batch = list(chunk_data(clean_data, 25))[0]

print(len(batch))
print(batch[0])
print(batch[1])

   s.no             question  \
0     1         குடியை மறக்க
1     2             செல்போன்
2     3        முகம் பளபளக்க
3     4  முகச்சுருக்கம் மறைய
4     5   உடல் மினுமினுப்பாக

                                              answer
0  வில்வ இலை, மிளகு, கொத்தமல்லி விதை இந்த மூன்றைய...
1  செல்போன் அடிக்கடி உபயோகித்தால் மூளை மந்தம், கா...
2  நாட்டு வாழைப்பழம் நன்றாக பழுத்தது. ஆலிவ் ஆயில்...
3             முட்டைகோஸ் சாறை முகத்தில் தடவி வரலாம்.
4  இரவில் படுக்கப் போகும் முன் தேன், குங்குமப்பூ....
Total rows: 1082
[{'id': 1, 'question': 'குடியை மறக்க', 'answer': 'வில்வ இலை, மிளகு, கொத்தமல்லி விதை இந்த மூன்றையும் 300 மி. தண்ணீர் விட்டு கொதிக்க வைத்து இறக்கவும். வாரம் ஒரு முறை மாதம் 4 முறை கொடுக்கவும். பலன் கிடைக்கும்'}, {'id': 2, 'question': 'செல்போன்', 'answer': 'செல்போன் அடிக்கடி உபயோகித்தால் மூளை மந்தம், காது கோளாறு போன்றவை ஏற்படும்'}, {'id': 3, 'question': 'முகம் பளபளக்க', 'answer': 'நாட்டு வாழைப்பழம் நன்றாக பழுத்தது. ஆலிவ் ஆயில் சேர்த்து பிசைந்து முகத்தில் தடவி 1 மணி நேரம் கழித்து முகம் கழுவி வரலாம்'}]
25
{'id': 1, 'question': 'குடியை மறக்க', 'answer': 'வில்வ இலை, மிளகு, கொத்தமல்லி விதை இந்த மூன்றையும் 300 மி. தண்ணீர் விட்டு கொதிக்க வைத்து இறக்கவும். வாரம் ஒரு முறை மாதம் 4 முறை கொடுக்கவும். பலன் கிடைக்கும்'}
{'id': 2, 'question': 'செல்போன்', 'answer': 'செல்போன் அடிக்கடி உபயோகித்தால் மூளை மந்தம், காது கோளாறு போன்றவை ஏற்படும்'}

### Step 4: LLM core

#### Step 4.1 classify lesson names

In [12]:
import os
import json
import time
import pandas as pd
from dotenv import load_dotenv
from groq import Groq

# Load API key
load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")

if not GROQ_API_KEY:
    raise ValueError("GROQ_API_KEY not found. Add it to your .env file.")

groq_client = Groq(api_key=GROQ_API_KEY)

# Load cleaned dataset
df = pd.read_csv("siddha_clean.csv")

print("Total rows:", len(df))
print(df.head())

Total rows: 1082
   s.no             question  \
0     1         குடியை மறக்க
1     2             செல்போன்
2     3        முகம் பளபளக்க
3     4  முகச்சுருக்கம் மறைய
4     5   உடல் மினுமினுப்பாக

                                              answer
0  வில்வ இலை, மிளகு, கொத்தமல்லி விதை இந்த மூன்றைய...
1  செல்போன் அடிக்கடி உபயோகித்தால் மூளை மந்தம், கா...
2  நாட்டு வாழைப்பழம் நன்றாக பழுத்தது. ஆலிவ் ஆயில்...
3             முட்டைகோஸ் சாறை முகத்தில் தடவி வரலாம்.
4  இரவில் படுக்கப் போகும் முன் தேன், குங்குமப்பூ....

In [13]:
# Convert CSV rows into clean dict format
clean_data = []

for _, row in df.iterrows():
    q = str(row["question"]).strip()
    a = str(row["answer"]).strip()

    q = " ".join(q.split())
    a = " ".join(a.split())

    clean_data.append({
        "id": int(row["s.no"]),
        "question": q,
        "answer": a
    })

print("Prepared rows:", len(clean_data))
print(clean_data[:2])

Prepared rows: 1082
[{'id': 1, 'question': 'குடியை மறக்க', 'answer': 'வில்வ இலை, மிளகு, கொத்தமல்லி விதை இந்த மூன்றையும் 300 மி. தண்ணீர் விட்டு கொதிக்க வைத்து இறக்கவும். வாரம் ஒரு முறை மாதம் 4 முறை கொடுக்கவும். பலன் கிடைக்கும்'}, {'id': 2, 'question': 'செல்போன்', 'answer': 'செல்போன் அடிக்கடி உபயோகித்தால் மூளை மந்தம், காது கோளாறு போன்றவை ஏற்படும்'}]

In [14]:
ALLOWED_LESSONS = [
    "Skin Care and Beauty",
    "Hair Care",
    "Women Health",
    "Pregnancy and Postpartum",
    "Child Care",
    "Male Health",
    "Digestive Health",
    "Respiratory Health",
    "Fever and Infections",
    "ENT, Mouth and Dental",
    "Eye Care",
    "Pain, Joints and Nerves",
    "Wounds, Burns and Injuries",
    "Heart, Blood and Circulation",
    "Liver, Bile and Jaundice",
    "Kidney, Urinary and Diabetes",
    "Mental Health, Sleep and Memory",
    "Poison, Bites and Stings",
    "General Wellness and Body Strength"
]

In [15]:
def chunk_data(data, size=20):
    for i in range(0, len(data), size):
        yield data[i:i + size]


def build_lesson_prompt(batch):
    compact_batch = [
        {
            "id": int(x["id"]),
            "question": x["question"]
        }
        for x in batch
    ]

    return f"""
Return ONLY a valid JSON array.
No explanation.
No markdown.
No code fences.

Classify each Siddha medicine question into exactly ONE lesson.

Allowed lessons:
{ALLOWED_LESSONS}

Return format:
[
  {{
    "id": 1,
    "lesson_en": "Skin Care and Beauty"
  }}
]

Rules:
- Use only the exact lesson names from the allowed list.
- Do not create new lesson names.
- Include every input id exactly once.
- Do not include answer text.
- If the question is about face, skin glow, pimples, itching, scabies, rashes, scars, or complexion, choose "Skin Care and Beauty".
- If the question is about hair growth, dandruff, lice, baldness, grey hair, or hair fall, choose "Hair Care".
- If the question is about menstruation, uterus, white discharge, female infertility, breast health, or lactation, choose "Women Health".
- If the question is about pregnancy, fetus, delivery, miscarriage, or postpartum recovery, choose "Pregnancy and Postpartum".
- If the question is specifically about babies or children, choose "Child Care".
- If the question is about male fertility, semen, virility, male reproductive organs, or male sexual strength, choose "Male Health".
- If the question is about stomach, digestion, constipation, diarrhea, piles, gas, vomiting, appetite, hiccups, mouth ulcer connected with digestion, or intestinal worms, choose "Digestive Health".
- If the question is about cough, cold, phlegm, asthma, breathing, lungs, chest congestion, or respiratory allergy, choose "Respiratory Health".
- If the question is about fever, typhoid, malaria, smallpox, infection, or infectious disease, choose "Fever and Infections".
- If the question is about ear, nose, throat, mouth, tongue, lips, teeth, gums, voice, or bad breath, choose "ENT, Mouth and Dental".
- If the question is about eyes or eyesight, choose "Eye Care".
- If the question is about body pain, joint pain, nerve pain, back pain, neck pain, paralysis, sprain, swelling, leg/hand pain, or vatha conditions, choose "Pain, Joints and Nerves".
- If the question is about cuts, wounds, burns, ulcers, injuries, bleeding wounds, bed sores, nail wounds, or corns, choose "Wounds, Burns and Injuries".
- If the question is about heart, blood pressure, blood purification, anemia, circulation, chest pain related to heart, or blood disorders, choose "Heart, Blood and Circulation".
- If the question is about liver, bile, pitham, jaundice, spleen, or gall bladder, choose "Liver, Bile and Jaundice".
- If the question is about urine, kidney, urinary stones, diabetes, excessive urination, or urinary burning, choose "Kidney, Urinary and Diabetes".
- If the question is about mind, brain, memory, sleep, dizziness, mental illness, or hysteria, choose "Mental Health, Sleep and Memory".
- If the question is about snake bite, dog bite, scorpion sting, insect bite, poison, venom, or toxic bites, choose "Poison, Bites and Stings".
- If none of the above fit, choose "General Wellness and Body Strength".

Data:
{json.dumps(compact_batch, ensure_ascii=False)}
"""

In [16]:
all_assignments = []

batches = list(chunk_data(clean_data, size=20))

print("Total batches:", len(batches))

for batch_no, batch in enumerate(batches, start=1):
    print(f"Processing batch {batch_no}/{len(batches)}")

    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": build_lesson_prompt(batch)
            }
        ],
        temperature=0,
        max_completion_tokens=1500
    )

    raw_output = response.choices[0].message.content.strip()

    try:
        assignments = json.loads(raw_output)
    except json.JSONDecodeError:
        print("JSON parse failed in batch:", batch_no)
        print(raw_output)
        raise

    input_ids = {item["id"] for item in batch}
    output_ids = {item["id"] for item in assignments}

    missing_ids = input_ids - output_ids
    extra_ids = output_ids - input_ids

    if missing_ids:
        raise ValueError(f"Missing ids in batch {batch_no}: {missing_ids}")

    if extra_ids:
        raise ValueError(f"Extra ids in batch {batch_no}: {extra_ids}")

    for item in assignments:
        if item["lesson_en"] not in ALLOWED_LESSONS:
            raise ValueError(f"Invalid lesson in batch {batch_no}: {item}")

    all_assignments.extend(assignments)

    time.sleep(1)

print("Classification completed")
print("Total classified:", len(all_assignments))

Total batches: 55
Processing batch 1/55
Processing batch 2/55
Processing batch 3/55
Processing batch 4/55
Processing batch 5/55
Processing batch 6/55
Processing batch 7/55
Processing batch 8/55
Processing batch 9/55
Processing batch 10/55
Processing batch 11/55
Processing batch 12/55
Processing batch 13/55
Processing batch 14/55
Processing batch 15/55
Processing batch 16/55
Processing batch 17/55
Processing batch 18/55
Processing batch 19/55
Processing batch 20/55
Processing batch 21/55
Processing batch 22/55
Processing batch 23/55
Processing batch 24/55
Processing batch 25/55
Processing batch 26/55
Processing batch 27/55
Processing batch 28/55
Processing batch 29/55
Processing batch 30/55
Processing batch 31/55
Processing batch 32/55
Processing batch 33/55
Processing batch 34/55
Processing batch 35/55
Processing batch 36/55
Processing batch 37/55
Processing batch 38/55
Processing batch 39/55
Processing batch 40/55
Processing batch 41/55

RateLimitError: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kpbtq09peg1sj17gws7fmskt` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99113, Requested 2231. Please try again in 19m21.216s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

In [17]:
import pandas as pd

# Save whatever was completed before rate limit
partial_lesson_df = pd.DataFrame(all_assignments)

print("Saved classifications:", len(partial_lesson_df))
print(partial_lesson_df.head())
print(partial_lesson_df["lesson_en"].value_counts())

partial_lesson_df.to_csv(
    "siddha_lesson_assignments_partial.csv",
    index=False,
    encoding="utf-8"
)

print("Saved as siddha_lesson_assignments_partial.csv")

Saved classifications: 800
   id                           lesson_en
0   1  General Wellness and Body Strength
1   2  General Wellness and Body Strength
2   3                Skin Care and Beauty
3   4                Skin Care and Beauty
4   5  General Wellness and Body Strength
lesson_en
Digestive Health                      115
Pain, Joints and Nerves                78
Respiratory Health                     72
Wounds, Burns and Injuries             71
Skin Care and Beauty                   65
ENT, Mouth and Dental                  62
Liver, Bile and Jaundice               54
Kidney, Urinary and Diabetes           51
Heart, Blood and Circulation           40
Women Health                           38
General Wellness and Body Strength     35
Eye Care                               28
Mental Health, Sleep and Memory        23
Fever and Infections                   23
Hair Care                              19
Male Health                            12
Child Care                              8
Pregnancy and Postpartum                5
Poison, Bites and Stings                1
Name: count, dtype: int64
Saved as siddha_lesson_assignments_partial.csv

In [18]:
partial_final_df = df.merge(
    partial_lesson_df,
    left_on="s.no",
    right_on="id",
    how="left"
)

partial_final_df = partial_final_df[["s.no", "question", "answer", "lesson_en"]]

print("Total rows:", len(partial_final_df))
print("Classified rows:", partial_final_df["lesson_en"].notna().sum())
print("Missing rows:", partial_final_df["lesson_en"].isna().sum())

partial_final_df.to_csv(
    "siddha_with_lessons_partial.csv",
    index=False,
    encoding="utf-8"
)

print("Saved as siddha_with_lessons_partial.csv")

Total rows: 1082
Classified rows: 800
Missing rows: 282
Saved as siddha_with_lessons_partial.csv

In [20]:
import pandas as pd

# Load original clean dataset
df = pd.read_csv("siddha_clean.csv")

# Load whatever lesson classifications were saved
lesson_df = pd.read_csv("siddha_lesson_assignments_partial.csv")

print("Original rows:", len(df))
print("Classified rows before cleaning:", len(lesson_df))

lesson_df.head()

Original rows: 1082
Classified rows before cleaning: 800

   id                           lesson_en
0   1  General Wellness and Body Strength
1   2  General Wellness and Body Strength
2   3                Skin Care and Beauty
3   4                Skin Care and Beauty
4   5  General Wellness and Body Strength

In [21]:
final_df = df.merge(
    partial_lesson_df,
    left_on="s.no",
    right_on="id",
    how="left"
)

final_df = final_df[["s.no", "question", "answer", "lesson_en"]]

print("Total rows:", len(final_df))
print("Rows with lesson:", final_df["lesson_en"].notna().sum())
print("Rows without lesson:", final_df["lesson_en"].isna().sum())

Total rows: 1082
Rows with lesson: 800
Rows without lesson: 282

In [22]:
usable_df = final_df.dropna(subset=["lesson_en"]).copy()

usable_df["question"] = usable_df["question"].astype(str).str.strip()
usable_df["answer"] = usable_df["answer"].astype(str).str.strip()
usable_df["lesson_en"] = usable_df["lesson_en"].astype(str).str.strip()

usable_df = usable_df[
    (usable_df["question"] != "") &
    (usable_df["answer"] != "") &
    (usable_df["lesson_en"] != "")
]

usable_df = usable_df.sort_values(["lesson_en", "s.no"]).reset_index(drop=True)

print("Usable rows:", len(usable_df))
print(usable_df["lesson_en"].value_counts())

usable_df.to_csv(
    "siddha_with_lessons_clean.csv",
    index=False,
    encoding="utf-8"
)

print("Saved as siddha_with_lessons_clean.csv")

Usable rows: 800
lesson_en
Digestive Health                      115
Pain, Joints and Nerves                78
Respiratory Health                     72
Wounds, Burns and Injuries             71
Skin Care and Beauty                   65
ENT, Mouth and Dental                  62
Liver, Bile and Jaundice               54
Kidney, Urinary and Diabetes           51
Heart, Blood and Circulation           40
Women Health                           38
General Wellness and Body Strength     35
Eye Care                               28
Fever and Infections                   23
Mental Health, Sleep and Memory        23
Hair Care                              19
Male Health                            12
Child Care                              8
Pregnancy and Postpartum                5
Poison, Bites and Stings                1
Name: count, dtype: int64
Saved as siddha_with_lessons_clean.csv

### Step 5:Merge and make it as Markdown

In [28]:
import re
from pathlib import Path
import pandas as pd

df = pd.read_csv("siddha_with_lessons_clean.csv")

print("Rows loaded:", len(df))
print(df["lesson_en"].value_counts())

Rows loaded: 800
lesson_en
Digestive Health                      115
Pain, Joints and Nerves                78
Respiratory Health                     72
Wounds, Burns and Injuries             71
Skin Care and Beauty                   65
ENT, Mouth and Dental                  62
Liver, Bile and Jaundice               54
Kidney, Urinary and Diabetes           51
Heart, Blood and Circulation           40
Women Health                           38
General Wellness and Body Strength     35
Eye Care                               28
Fever and Infections                   23
Mental Health, Sleep and Memory        23
Hair Care                              19
Male Health                            12
Child Care                              8
Pregnancy and Postpartum                5
Poison, Bites and Stings                1
Name: count, dtype: int64

In [29]:
LESSON_ORDER = [
    "Skin Care and Beauty",
    "Hair Care",
    "Women Health",
    "Pregnancy and Postpartum",
    "Child Care",
    "Male Health",
    "Digestive Health",
    "Respiratory Health",
    "Fever and Infections",
    "ENT, Mouth and Dental",
    "Eye Care",
    "Pain, Joints and Nerves",
    "Wounds, Burns and Injuries",
    "Heart, Blood and Circulation",
    "Liver, Bile and Jaundice",
    "Kidney, Urinary and Diabetes",
    "Mental Health, Sleep and Memory",
    "Poison, Bites and Stings",
    "General Wellness and Body Strength"
]

def clean_text(text):
    text = str(text).strip()
    text = " ".join(text.split())
    return text

In [30]:
lines = []

lines.append("# Siddha Vaithiyam Knowledge Base")
lines.append("")
lines.append("This knowledge base contains Siddha medicine question-answer records grouped by lesson.")
lines.append("")
lines.append("Important: This content is for educational use only and should not replace professional medical advice.")
lines.append("")
lines.append("---")
lines.append("")

# Index section
lines.append("# Index")
lines.append("")

lesson_summaries = []

for lesson_number, lesson_name in enumerate(LESSON_ORDER, start=1):
    lesson_df = df[df["lesson_en"] == lesson_name].copy()

    if lesson_df.empty:
        continue

    lesson_summaries.append({
        "lesson_number": lesson_number,
        "lesson_name": lesson_name,
        "count": len(lesson_df)
    })

for item in lesson_summaries:
    lines.append(
        f'{item["lesson_number"]}. {item["lesson_name"]} - {item["count"]} Q&A items'
    )

lines.append("")
lines.append("## Summary")
lines.append("")
lines.append(f"- Total lessons: {len(lesson_summaries)}")
lines.append(f"- Total Q&A items: {len(df)}")
lines.append("")
lines.append("---")
lines.append("")

In [31]:
# Lesson sections
for item in lesson_summaries:
    lesson_number = item["lesson_number"]
    lesson_name = item["lesson_name"]

    lesson_df = df[df["lesson_en"] == lesson_name].copy()
    lesson_df = lesson_df.sort_values("s.no")

    lines.append(f"# Lesson {lesson_number}: {lesson_name}")
    lines.append("")
    lines.append(f"Total Q&A items: {len(lesson_df)}")
    lines.append("")
    lines.append("---")
    lines.append("")

    for _, row in lesson_df.iterrows():
        item_id = int(row["s.no"])
        question = clean_text(row["question"])
        answer = clean_text(row["answer"])

        lines.append(f"## {item_id}. {question}")
        lines.append("")
        lines.append("**Answer:**")
        lines.append("")
        lines.append(answer)
        lines.append("")
        lines.append("---")
        lines.append("")

output_path = Path("siddha_knowledge_base.md")
output_path.write_text("\n".join(lines), encoding="utf-8")

print("Saved:", output_path)
print("Total lessons:", len(lesson_summaries))
print("Total Q&A items:", len(df))

Saved: siddha_knowledge_base.md
Total lessons: 19
Total Q&A items: 800

In [32]:
print(Path("siddha_knowledge_base.md").read_text(encoding="utf-8")[:3000])

# Siddha Vaithiyam Knowledge Base

This knowledge base contains Siddha medicine question-answer records grouped by lesson.

Important: This content is for educational use only and should not replace professional medical advice.

---

# Index

1. Skin Care and Beauty - 65 Q&A items
2. Hair Care - 19 Q&A items
3. Women Health - 38 Q&A items
4. Pregnancy and Postpartum - 5 Q&A items
5. Child Care - 8 Q&A items
6. Male Health - 12 Q&A items
7. Digestive Health - 115 Q&A items
8. Respiratory Health - 72 Q&A items
9. Fever and Infections - 23 Q&A items
10. ENT, Mouth and Dental - 62 Q&A items
11. Eye Care - 28 Q&A items
12. Pain, Joints and Nerves - 78 Q&A items
13. Wounds, Burns and Injuries - 71 Q&A items
14. Heart, Blood and Circulation - 40 Q&A items
15. Liver, Bile and Jaundice - 54 Q&A items
16. Kidney, Urinary and Diabetes - 51 Q&A items
17. Mental Health, Sleep and Memory - 23 Q&A items
18. Poison, Bites and Stings - 1 Q&A items
19. General Wellness and Body Strength - 35 Q&A items

## Summary

- Total lessons: 19
- Total Q&A items: 800

---

# Lesson 1: Skin Care and Beauty

Total Q&A items: 65

---

## 3. முகம் பளபளக்க

**Answer:**

நாட்டு வாழைப்பழம் நன்றாக பழுத்தது. ஆலிவ் ஆயில் சேர்த்து பிசைந்து முகத்தில் தடவி 1 மணி நேரம் கழித்து முகம் கழுவி வரலாம்

---

## 4. முகச்சுருக்கம் மறைய

**Answer:**

முட்டைகோஸ் சாறை முகத்தில் தடவி வரலாம்.

---

## 6. உடல் நிறம் பளபளக்க

**Answer:**

அவரி இலையை சுத்தம் செய்து நன்கு உலர்த்தி தூளாக்கி தினமும் 5 கிராம் காலை உணவிற்க பின் சாப்பிடவும்

---

## 8. முக வசீகரம்

**Answer:**

சந்தன கட்டை எலுமிச்சை சாறில் உரைத்து பூசலாம்

---

## 9. முகம் பிரகாசமடைய

**Answer:**

கானாவாழை, மாவிலை சமஅளவு எடுத்து காய்ச்சி வடிகட்டி அதை முகத்தில் தடவி காயவிட்டு அரை மணிநேரம் கழித்து கழுவவும்.

---

## 10. மேனி பளபளப்பு பெற

**Answer:**

ஆரஞ்சு பழத்தை தொடர்ந்து சாப்பிட்டு வரலாம்.

---

## 11. தோல் வழவழப்பாக

**Answer:**

மருதாணி இலையை அரைத்து கருப்பு தோல் மீது தேய்த்து வந்தால் கருப்பு மாறும்

---

## 12. உடல் சிவப்பாக மாற

**Answer:**

வெள்ளரிக்காய், மஞ்சள், வேப்பம்பூ சேர்த்து அரைத்து உடலில் பூசி குளித்து வர குணமாகும்

---

## 14. முகம் அழகு கூட

**Answer:**

அருகம்புல்லை நீர்விட்டு அரைத்து வடித்து பின் வெல்லம் சேர்த்து பருகிவர உடலழகும் முக அழகும் கூடும்.

---

## 61. விலாவலி தீர

**Answer:**

துளசி இலை, இஞ்சி, தாமரைவேர் அரைத்து கொதிக்க வைத்து பற்றிட விலாவலி தீரும்.

---

## 78. சீலைபேன் ஒழிய

**Answer:**

நாய் துளசி இலையுடன் வசம்பு சேர்த்து அரைத்து உடல் முழுவதும் பூசிக் குளிக்கலாம்.

---

## 79. படர் தாமரை தீர

**Answer:**

சந்தனகட்டையை எலுமிச்சைச் சாற்றில் உரைத்து தடவ வேண்டும்.

---

## 80. படர் தாமரை குணமடைய

**Answer:**

பூவரசு காயின் சாற்றை தடவவும்.

---

## 81. நமைச்சல் சிரங்கு தீர

**Answer:**

துளசி இலையை அரைத்து பூசி குளிக்க வேண்டும்.

---

## 82. தேமல் சரியாக

**Answer:**

கமலா ஆரஞ்சு தோலை வெயிலில் உலர்த்தி பொடி செய்து தினமும் உடம்பிற்கு தேய்த்து குளித்து வரலாம்

---

## 83. சருமநோய்

**Answer:**

மஞ்சள், வேப்பிலையை அரைத்து பூச குணமாகும்.

---

## 84. தேமல் படை குணமாக

**Answer:**

நாயுருவி இலை சாறை தடவி வரலாம்.

---

## 8

## Part - 2

In [34]:
import json
import pandas as pd
from pathlib import Path

df = pd.read_csv("siddha_with_lessons_clean.csv")

LESSON_ORDER = [
    "Skin Care and Beauty",
    "Hair Care",
    "Women Health",
    "Pregnancy and Postpartum",
    "Child Care",
    "Male Health",
    "Digestive Health",
    "Respiratory Health",
    "Fever and Infections",
    "ENT, Mouth and Dental",
    "Eye Care",
    "Pain, Joints and Nerves",
    "Wounds, Burns and Injuries",
    "Heart, Blood and Circulation",
    "Liver, Bile and Jaundice",
    "Kidney, Urinary and Diabetes",
    "Mental Health, Sleep and Memory",
    "Poison, Bites and Stings",
    "General Wellness and Body Strength"
]

def clean_text(text):
    text = str(text).strip()
    text = " ".join(text.split())
    return text

tree = {
    "title": "Siddha Vaithiyam Knowledge Base",
    "description": "Siddha medicine question-answer records grouped by lesson.",
    "total_items": int(len(df)),
    "lessons": []
}

for lesson_id, lesson_name in enumerate(LESSON_ORDER, start=1):
    lesson_df = df[df["lesson_en"] == lesson_name].copy()

    if lesson_df.empty:
        continue

    lesson_df = lesson_df.sort_values("s.no")

    lesson = {
        "lesson_id": lesson_id,
        "lesson_name": lesson_name,
        "items_count": int(len(lesson_df)),
        "items": []
    }

    for _, row in lesson_df.iterrows():
        lesson["items"].append({
            "id": int(row["s.no"]),
            "question": clean_text(row["question"]),
            "answer": clean_text(row["answer"])
        })

    tree["lessons"].append(lesson)

Path("siddha_tree.json").write_text(
    json.dumps(tree, ensure_ascii=False, indent=2),
    encoding="utf-8"
)

print("Saved siddha_tree.json")
print("Total lessons:", len(tree["lessons"]))
print("Total items:", tree["total_items"])

Saved siddha_tree.json
Total lessons: 19
Total items: 800

In [35]:
import json
from pathlib import Path

TREE_PATH = Path("siddha_tree.json")

tree = json.loads(TREE_PATH.read_text(encoding="utf-8"))

print(f"Top-level lessons: {len(tree['lessons'])}")
print(f"Total items: {tree['total_items']}")
print()
print("First lesson preview:")
print(json.dumps(tree["lessons"][0], ensure_ascii=False, indent=2)[:1000])

Top-level lessons: 19
Total items: 800

First lesson preview:
{
  "lesson_id": 1,
  "lesson_name": "Skin Care and Beauty",
  "items_count": 65,
  "items": [
    {
      "id": 3,
      "question": "முகம் பளபளக்க",
      "answer": "நாட்டு வாழைப்பழம் நன்றாக பழுத்தது. ஆலிவ் ஆயில் சேர்த்து பிசைந்து முகத்தில் தடவி 1 மணி நேரம் கழித்து முகம் கழுவி வரலாம்"
    },
    {
      "id": 4,
      "question": "முகச்சுருக்கம் மறைய",
      "answer": "முட்டைகோஸ் சாறை முகத்தில் தடவி வரலாம்."
    },
    {
      "id": 6,
      "question": "உடல் நிறம் பளபளக்க",
      "answer": "அவரி இலையை சுத்தம் செய்து நன்கு உலர்த்தி தூளாக்கி தினமும் 5 கிராம் காலை உணவிற்க பின் சாப்பிடவும்"
    },
    {
      "id": 8,
      "question": "முக வசீகரம்",
      "answer": "சந்தன கட்டை எலுமிச்சை சாறில் உரைத்து பூசலாம்"
    },
    {
      "id": 9,
      "question": "முகம் பிரகாசமடைய",
      "answer": "கானாவாழை, மாவிலை சமஅளவு எடுத்து காய்ச்சி வடிகட்டி அதை முகத்தில் தடவி காயவிட்டு அரை மணிநேரம் கழித்து கழுவவும்."
    },
    {
      "id": 10,
      "question": "மேனி பளபளப்பு பெற",
      "answer": "

In [36]:
def print_siddha_tree(tree, max_items_per_lesson=5):
    print(tree["title"])
    print("Total lessons:", len(tree["lessons"]))
    print("Total items:", tree["total_items"])
    print()

    for lesson in tree["lessons"]:
        lesson_id = lesson["lesson_id"]
        lesson_name = lesson["lesson_name"]
        items_count = lesson["items_count"]

        print(f"Lesson {lesson_id}: {lesson_name} ({items_count} items)")

        for item in lesson["items"][:max_items_per_lesson]:
            print(f"  - [{item['id']}] {item['question']}")

        remaining = items_count - max_items_per_lesson

        if remaining > 0:
            print(f"  ... {remaining} more")

        print()

print_siddha_tree(tree)

Siddha Vaithiyam Knowledge Base
Total lessons: 19
Total items: 800

Lesson 1: Skin Care and Beauty (65 items)
  - [3] முகம் பளபளக்க
  - [4] முகச்சுருக்கம் மறைய
  - [6] உடல் நிறம் பளபளக்க
  - [8] முக வசீகரம்
  - [9] முகம் பிரகாசமடைய
  ... 60 more

Lesson 2: Hair Care (19 items)
  - [90] வேர் குரு
  - [93] சிரட்டை தைலம்
  - [517] இளவயது நரை மாற
  - [518] இளம் நரை மறைய
  - [519] இளநரை தீர, உடல் பலம் பெற
  ... 14 more

Lesson 3: Women Health (38 items)
  - [21] குழந்தையின்மை நீங்க
  - [22] கர்ப்பபை புழு நீங்க
  - [24] பிள்ளைப் பேறு உண்டாக
  - [25] கர்ப்பபை நோய்கள் தீர
  - [26] பெரும்பாடு தீர, கர்ப்பபை பலப்பட
  ... 33 more

Lesson 4: Pregnancy and Postpartum (5 items)
  - [55] கருவுற்ற தாய்மார்கள்
  - [56] கர்ப்பாயாச கோளாறு நீங்க
  - [57] கருச்சிதைவு ஏற்படாமல் இருக்க
  - [700] குழந்தை பிறப்பதற்கு முன்னும், பிறந்த பின்னும்
  - [705] கர்ப்ப காலத்தில் வாந்தி மட்டுபட

Lesson 5: Child Care (8 items)
  - [23] குழந்தை சிவப்பாக பிறக்க
  - [41] குழந்தைகளுக்கு
  - [42] போலியோ சொட்டு மருந்து
  - [44] குறைமாத குழந்தை
  - [47] வயிறு பெருத்து உடல் சிறியதாக உள்ள குழந்தைகளுக்கு
  ... 3 more

Lesson 6: Male Health (12 items)
  - [18] காமபெருக்கி
  - [19] இல்லறவாழ்வில் திருப்தியில்லாமல் இருந்தால்
  - [20] காமம் பெருக்க
  - [67] ஆண்மலடு நீங்க
  - [68] ஆண்மை குறைவு நீங்க
  ... 7 more

Lesson 7: Digestive Health (115 items)
  - [46] அக்கி குணமாக
  - [50] வயிற்றுப்புண் ஆற
  - [51] குழந்தைகளுக்கு ஜீரண டானிக்
  - [124] கபரோகம் தீர
  - [161] இரைப்பு தீர
  ... 110 more

Lesson 8: Respiratory Health (72 items)
  - [49] குழந்தைகளுக்கு ஏற்படும் தொடர் இருமலுக்கு
  - [53] கக்குவான் இருமல் தீர
  - [108] சளி காய்ச்சல் தீர
  - [109] சளிக் காய்ச்சல் குணமாக
  - [114] இருமல், சளிகாய்ச்சல்
  ... 67 more

Lesson 9: Fever and Infections (23 items)
  - [52] காய்ச்சல் குணமாக
  - [99] காய்ச்சல் தீர
  - [100] மலேரியா காய்ச்சல் குணமாக
  - [101] பித்த காய்ச்சல் தீர
  - [102] எப்படிப்பட்ட காய்ச்சலும் தீர
  ... 18 more

Lesson 10: ENT, Mouth and Dental (62 items)
  - [257] வாய் திக்குதல்
  - [258] பேசும் திறன் அதிகரிக்க
  - [259] திக்கி பேசுதல் குணமாக
  - [260] திக்கி பேசுதல் சரியாக
  - [335] பல் உறுதியாக
  ... 57 more

Lesson 11: Eye Care (28 items)
  - [201] கண்டமாலை வீக்கம் கரைய
  - [202] நரம் இசிவு சிரங்கு, கண்டமாலை தீர
  - [203] கண்டமாலை புண் தீர
  - [415] கண்கள் ஒளி
  - [416] கண் எரிச்சல்
  ... 23 more

Lesson 12: Pain, Joints and Nerves (78 items)
  - [59] இடுப்பு வலி குணமடைய
  - [62] இடுப்பு வலி தீர
  - [111] சன்னி இழுப்பு
  - [123] எலும்புருக்கி நோய் குணமாக
  - [198] கழுத்து வலி குணமாக
  ... 73 more

Lesson 13: Wounds, Burns and Injuries (71 items)
  - [91] புண், சிரங்கு தீர
  - [172] சிராய்ப்பு காயங்களுக்கு
  - [173] எல்லாவித புண் புரைகளும் தீர
  - [174] வெட்டுக்காயம் குணமாக
  - [175] வெட்டுக்காயம் சீக்கிரம் ஆற
  ... 66 more

Lesson 14: Heart, Blood and Circulation (40 items)
  - [154] இதய நோய் குணமாக
  - [162] மார்பு வலி
  - [206] இதய படபடப்பு குறைய
  - [207] இதயம் படபடப்பு நீங்க
  - [208] இதய நோய் சாந்தமாக
  ... 35 more

Lesson 15: Liver, Bile and Jaundice (54 items)
  - [121] பித்த சுரம் தீர
  - [122] கபம் உடைந்து வெளியேற
  - [125] கிராணி, குன்மம், கபநோய்கள் தீர
  - [126] கபம் குணமாக
  - [127] கபம் நீங்க
  ... 49 more

Lesson 16: Kidney, Urinary and Diabetes (51 items)
  - [475] நீரடைப்பு சரியாக
  - [476] நீர் கட்டை உடைக்க
  - [478] நீர்தாரை எரிச்சல் தீர
  - [479] மூத்திரக்கடுப்பு தீர
  - [480] எரிச்சல் குணமாக
  ... 46 more

Lesson 17: Mental Health, Sleep and Memory (23 items)
  - [43] குழந்தைகளுக்கு தாழ்வு மனப்பான்மை உருவாகாமல் இருக்க
  - [300] இரவில் அதிகநேரம் கண் விழித்திருத்தலைத் தவிர்த்தல்
  - [546] ஹிஸ்டிரியா நோய்
  - [547] பைத்தியம் தீர
  - [548] பித்தத்தினால் ஏற்படும் பைத்தியம் குணமாக
  ... 18 more

Lesson 18: Poison, Bites and Stings (1 items)
  - [118] நச்சு காய்ச்சல் போக

Lesson 19: General Wellness and Body Strength (35 items)
  - [1] குடியை மறக்க
  - [2] செல்போன்
  - [5] உடல் மினுமினுப்பாக
  - [7] உடல் வனப்பு உண்டாக
  - [13] உடம்பு பொலிவு பெற
  ... 30 more

In [37]:
def count_retrievable_items(tree):
    total_lessons = len(tree["lessons"])
    total_items = sum(lesson["items_count"] for lesson in tree["lessons"])

    return total_lessons, total_items

total_lessons, total_items = count_retrievable_items(tree)

print(f"Total lessons: {total_lessons}")
print(f"Total retrievable Q&A items: {total_items}")
print("Each Q&A item = one retrievable chunk.")

Total lessons: 19
Total retrievable Q&A items: 800
Each Q&A item = one retrievable chunk.

### Step 1: Select Relevant Lessons

In [54]:
import os
import json
import re
from pathlib import Path
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

GRO_API_KEY = os.getenv("GRO_API_KEY")

if not GRO_API_KEY:
    raise ValueError("GROQ_API_KEY missing in .env")

groq_client = Groq(api_key=GRO_API_KEY)

tree = json.loads(Path("siddha_tree.json").read_text(encoding="utf-8"))

print("Tree loaded")
print("Lessons:", len(tree["lessons"]))
print("Items:", tree["total_items"])

Tree loaded
Lessons: 19
Items: 800

In [63]:
def compact_json(data):
    return json.dumps(data, ensure_ascii=False, separators=(",", ":"))


def parse_json_response(text):
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if match:
            return json.loads(match.group())
        return {}

In [64]:
def groq_json(prompt, model="llama-3.3-70b-versatile", max_tokens=300):
    response = groq_client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0,
        max_completion_tokens=max_tokens
    )

    content = response.choices[0].message.content.strip()
    return parse_json_response(content)

In [65]:
def llm_select_lessons(query, tree, model="llama-3.3-70b-versatile"):
    lesson_index = []

    for lesson in tree["lessons"]:
        sample_questions = [
            item["question"]
            for item in lesson["items"][:8]
        ]

        lesson_index.append({
            "lesson_id": lesson["lesson_id"],
            "lesson_name": lesson["lesson_name"],
            "items_count": lesson["items_count"],
            "sample_questions": sample_questions
        })

    prompt = f"""
You are selecting the most relevant lessons from a Siddha medicine knowledge tree.

User query:
{query}

Lesson index:
{compact_json(lesson_index)}

Return ONLY valid JSON.

Format:
{{
  "thinking": "short reason",
  "lesson_ids": [1, 2]
}}

Rules:
- Select 1 to 2 lesson_ids.
- Prefer the single most specific lesson when the query clearly belongs to one lesson.
- Choose lessons most likely to contain the answer.
- Do not create new lesson IDs.
- Keep thinking short.
"""

    result = groq_json(prompt, model=model, max_tokens=300)

    lesson_ids = result.get("lesson_ids", [])

    valid_ids = {lesson["lesson_id"] for lesson in tree["lessons"]}
    lesson_ids = [x for x in lesson_ids if x in valid_ids]

    return {
        "thinking": result.get("thinking", ""),
        "lesson_ids": lesson_ids
    }

In [66]:
def llm_select_items(query, tree, lesson_ids, model="llama-3.3-70b-versatile"):
    candidates = []

    for lesson in tree["lessons"]:
        if lesson["lesson_id"] in lesson_ids:
            for item in lesson["items"]:
                candidates.append({
                    "node_id": f"Q{item['id']}",
                    "id": item["id"],
                    "lesson_name": lesson["lesson_name"],
                    "question": item["question"]
                })

    if not candidates:
        return {
            "thinking": "No candidate lessons found.",
            "node_list": []
        }

    prompt = f"""
You are selecting relevant Q&A nodes from a Siddha medicine knowledge tree.

User query:
{query}

Candidate Q&A nodes:
{compact_json(candidates)}

Return ONLY valid JSON.

Format:
{{
  "thinking": "short reason",
  "node_list": ["Q10", "Q25"]
}}

Rules:
- Select 1 to 8 node_ids.
- Choose questions that directly match the user query.
- Do not create node_ids.
- If no relevant node exists, return an empty list.
- Keep thinking short.
"""

    result = groq_json(prompt, model=model, max_tokens=400)

    valid_node_ids = {item["node_id"] for item in candidates}
    node_list = result.get("node_list", [])
    node_list = [x for x in node_list if x in valid_node_ids]

    return {
        "thinking": result.get("thinking", ""),
        "node_list": node_list
    }

In [67]:
def find_nodes_by_ids(tree, target_node_ids):
    found = []

    target_node_ids = set(target_node_ids)

    for lesson in tree["lessons"]:
        for item in lesson["items"]:
            node_id = f"Q{item['id']}"

            if node_id in target_node_ids:
                found.append({
                    "node_id": node_id,
                    "lesson_id": lesson["lesson_id"],
                    "lesson_name": lesson["lesson_name"],
                    "id": item["id"],
                    "title": item["question"],
                    "text": item["answer"]
                })

    return found

In [68]:
def generate_answer(query, nodes, model="llama-3.3-70b-versatile"):
    if not nodes:
        return "இந்த கேள்விக்கு பொருத்தமான தகவல் இந்த knowledge tree-ல் கிடைக்கவில்லை."

    context_parts = []

    for node in nodes:
        context_parts.append(
            f"[Node: {node['node_id']} | Lesson: {node['lesson_name']}]\n"
            f"Question: {node['title']}\n"
            f"Answer: {node['text']}"
        )

    context = "\n\n---\n\n".join(context_parts)

    prompt = f"""
You are a Siddha medicine assistant.

Answer the user using ONLY the provided context.

User query:
{query}

Context:
{context}

Rules:
- Answer in Tamil.
- Use only the provided context.
- Do not invent remedies.
- Mention the matching source node IDs.
- Add a short safety note recommending a qualified doctor/practitioner for serious symptoms.

Answer:
"""

    response = groq_client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0,
        max_completion_tokens=700
    )

    return response.choices[0].message.content.strip()

In [69]:
def vectorless_rag(query, tree, model="llama-3.3-70b-versatile", verbose=True):
    if verbose:
        print("=" * 60)
        print("Query:", query)
        print("=" * 60)

    lesson_search = llm_select_lessons(query, tree, model=model)
    lesson_ids = lesson_search["lesson_ids"]

    if verbose:
        print("Lesson reasoning:", lesson_search["thinking"])
        print("Selected lesson IDs:", lesson_ids)

    item_search = llm_select_items(query, tree, lesson_ids, model=model)
    node_ids = item_search["node_list"]

    if verbose:
        print("Item reasoning:", item_search["thinking"])
        print("Selected node IDs:", node_ids)

    nodes = find_nodes_by_ids(tree, node_ids)

    if verbose:
        print("Retrieved nodes:", [n["title"] for n in nodes])

    answer = generate_answer(query, nodes, model=model)

    if verbose:
        print()
        print("Answer:")
        print(answer)

    return {
        "query": query,
        "lesson_ids": lesson_ids,
        "node_ids": node_ids,
        "nodes": nodes,
        "answer": answer
    }

In [70]:
result = vectorless_rag(
    query="மலச்சிக்கல் தீர என்ன செய்யலாம்?",
    tree=tree
)

============================================================
Query: மலச்சிக்கல் தீர என்ன செய்யலாம்?
============================================================
Lesson reasoning: Digestive health issues
Selected lesson IDs: [7]
Item reasoning: Direct match for மலச்சிக்கல் தீர
Selected node IDs: ['Q284', 'Q285', 'Q286', 'Q287', 'Q290', 'Q291', 'Q293', 'Q294']
Retrieved nodes: ['மலச்சிக்கல் தீர', 'மலச்சிக்கல் நீங்கி மூலம் கட்டுப்பட', 'மலச்சிக்கல் குணமாக', 'மலச்சிக்கல் நீங்க', 'மலச்சிக்கல் தீர', 'மலக்கட்டு தீர', 'மலச்சிக்கலை போக்க', 'மலம் கழித்தல் கிராணி']

Answer:
மலச்சிக்கல் தீர அகத்திகீரை வாரம் 1 நாள் சமைத்து உண்ண வேண்டும் (Node: Q284). பப்பாளிபழம் தினந்தோறும் சாப்பிட்டு வர குணமாகும் (Node: Q285). பார்லி அரிசி 20கிராம், புளிய இலை 40 கிராம் காய்ச்சி கஷாயமாக்கி குடித்து வரலாம் (Node: Q286). முளைக்கீரை சாப்பிட்டு வரலாம் (Node: Q287). இரவில் மாம்பழம் சாப்பிடலாம் (Node: Q290). முள்ளங்கி இலைசாறு 5மி.லி.3 வேளை சாப்பிட்டு வரலாம் (Node: Q291). நார்த்தங்காய் ஊறுகாய் சாப்பிடவும் (Node: Q293). பாதாளமூலி சதையை சிறுதுண்டுகளாக்கி மிளகுதூள் சேர்த்து சாப்பிட தீரும் (Node: Q294).

குறிப்பு: தீவிர அறிகுறிகள் இருந்தால், தகுதிவாய்ந்த மருத்துவரின் ஆலோசனையை நாடுங்கள

In [71]:
result = vectorless_rag(
    query="இருமல் குணமாக என்ன மருந்து?",
    tree=tree
)

============================================================
Query: இருமல் குணமாக என்ன மருந்து?
============================================================
Lesson reasoning: Cough is related to respiratory health
Selected lesson IDs: [8]
Item reasoning: Direct match for cough cure
Selected node IDs: ['Q140', 'Q157', 'Q158', 'Q762']
Retrieved nodes: ['இருமல் குணமாக', 'இருமல் குணமாக', 'கக்குவான் இருமல் வேகம் குறைய', 'இருமல் உடனே நிற்க']

Answer:
இருமல் குணமாக வெந்தயக்கீரை சமைத்து சாப்பிட்டு வரலாம் (Node: Q140). மாதுளம்பூ பொடியுடன் பனங்கற்கண்டு சேர்த்து காலை, மாலை 1 தேக்கரண்டி சாப்பிட்டு வரலாம் (Node: Q157). முற்றிய வெண்டைக்காயைச் சூப் செய்து குடித்து வந்தால் குணமாகும் (Node: Q762).

குறிப்பு: தீவிரமான இருமல் அறிகுறிகள் இருந்தால், தகுதிவாய்ந்த மருத்துவர்/சித்த மருத்துவரின் ஆலோசனையை நாடுங்கள்.